### ISSUE TITLE
Is it possible to use the plugin in UE 5.1.1? 

### ISSUE THREAD

**Issue by saravanan290702** [rlewicki/MeleeTrace#1]
if so, how do i just compile the plugin in ue 5.1.1? ty in advance

**Comment by rlewicki** [comment]
Hey, yes this should run just fine on 5.1 if you can compile it yourself!

6.10.2023 o 14:51 od ***@***.***:

**Comment by saravanan290702** [comment]
is the plugin replicated?

**Comment by rlewicki** [comment]
It doesn’t at the moment. Making it work in a listen server and dedicated server scenarios is on the roadmap for the plugin.

6.10.2023 o 15:20 od ***@***.***:

**Comment by saravanan290702** [comment]
ic ty for the reply, i will try to recompile back to 5.1.1, sigh prolly get 100's of errors

**Comment by rlewicki** [comment]
If you get errors please do share them here and I’ll try to prepare a new release that supports the UE 5.1

6.10.2023 o 17:40 od ***@***.***:

**Comment by rlewicki** [comment]
If you want to compile your own binaries you might need to move the plugin from the engine directory to your game directory. Also, delete the engine version from the `.uplugin` file.

I will try to prepare a package on marketplace for 5.1 version tomorrow as well if you would rather wait than doing all those shenanigans.

**Comment by saravanan290702** [comment]
oh cool iil close this issue and wait for a 5.1 release ty for the help.

**Comment by rlewicki** [comment]
@saravanan290702 hey just wanted to let you know that I have submitted plugin for version 5.1 to the marketplace. It will be available as soon as the marketplace submission team from Epic verifies everything is fine.

I also created new release available here on GitHub that compiles for UE 5.1 without any issues so if you prefer you can grab it here immediately without waiting.
