### ISSUE TITLE
UE5 5.2 Crashing

### ISSUE THREAD

**Issue by Polar2b** [rlewicki/MeleeTrace#12]
Plug-In crashes the engine when it is asked to do a trace. Normally is functional for a couple of minutes/traces before this. I don't have the project this was happening in anymore but if I have the time I'll replicate it, I already replicated it twice so it seems to be persistent.

**Comment by rlewicki** [comment]
Hi @Polar2b thank you for reporting the issue. Is there any chance you could attach a call stack from the crash that occurs on your side? I'd greatly appreciate help with pointing out where the issue could be so I can fix it!

**Comment by Polar2b** [comment]
Yea of course I should be able to recreate it later today or sometime this
weekend. Thank you.

**Comment by Polar2b** [comment]
Here you are: This should be all the info.
[SpellCharacterMerge_2.log](https://github.com/rlewicki/MeleeTrace/files/14628817/SpellCharacterMerge_2.log)


Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UnrealEditor_MeleeTrace!UMeleeTraceComponent::InternalStartTrace() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MeleeTrace\Source\MeleeTrace\Private\MeleeTraceComponent.cpp:236]
UnrealEditor_MeleeTrace!UMeleeTraceComponent::StartTraceWithContext() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MeleeTrace\Source\MeleeTrace\Private\MeleeTraceComponent.cpp:113]
UnrealEditor_MeleeTrace!UAnimNotifyState_MeleeTrace::NotifyBegin() [D:\build\U5M-Marketplace\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\MeleeTrace\Source\MeleeTrace\Private\AnimNotifyState_MeleeTrace.cpp:32]

UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

**Comment by rlewicki** [comment]
Thank you, this is very helpful! I can see where the issue is now! I will fix this tonight and submit new release to the marketplace and GitHub releases.

**Comment by rlewicki** [comment]
@Polar2b I've addressed this issue in latest release v1.3.2. If you could get latest and let me know if this fixes the issue for you I would be very grateful!

**Comment by Polar2b** [comment]
Just tested it out and It looks like it works, thank you so much, this helps a lot with prototyping. I'm glad I was able to help you out as well.

**Comment by rlewicki** [comment]
Cheers, I'm very happy to hear this solved your issues! Have a great day!
