### ISSUE TITLE
Editor errors, property is not initialized properly.

### ISSUE THREAD

**Issue by bibCorp** [rlewicki/MeleeTrace#15]
Hey, love the plugin and it's working well for us, but we are getting some editor errors:

![Screenshot 2024-04-29 112055](https://github.com/rlewicki/MeleeTrace/assets/149468818/9d86af50-cfab-410e-be86-4fb825b05fe9)

The plugin seems to work just fine despite this, but I would love to hear if you are familiar with this.

We are using UE 5.3.2, and our project is based on Lyra where our own game is implemented as a Modular Game Feature (which can always cause extra issues).

**Comment by rlewicki** [comment]
Hey @bibCorp thank you very much for reporting the issue. These errors are indeed harmless in most cases as all it's complaining about is that there is no default value assigned for some properties inside some structures but in this case those properties are also structs that already have reasonable default values.

Nevertheless, this is certainly something that should be addressed. I will try to have a look at it tonight and will let you know once I have an update on that.

**Comment by rlewicki** [comment]
@bibCorp I've pushed a fix for this issue. Seeing screenshot from the first post I assume you are building your own binaries right? If that's the case you can just grab the latest version of this repo in a zip file and replace `Source` directory. I will not then be publishing new release version as it's quite tidious to prepare binaries for all supported Unreal versions. Let me know if that works for you!

**Comment by bibCorp** [comment]
@rlewicki thank you for taking care of it so quickly!

**Comment by rlewicki** [comment]
No problem at all. Let me know if this fix works for you; if yes I'll close the issue

**Comment by bibCorp** [comment]
Yes it works! Thanks

**Comment by rlewicki** [comment]
Thanks for letting me know!
