### ISSUE TITLE
StaticMesh support?

### ISSUE THREAD

**Issue by coolzilj** [rlewicki/MeleeTrace#2]
Can you add support for StaticMesh?

**Comment by rlewicki** [comment]
Oh, I had no idea static meshes now support sockets! Thanks for sharing this, I will try to implement it this week and publish new version.

**Comment by coolzilj** [comment]
> @coolzilj hey, just wanted to let you know that if you get latest version from `master` branch there will be support for a static mesh components. It will take a while until it's available on a marketplace. Thank you for making this request and making me aware that static meshes also support sockets! The more you know! :D

Appreciate your hard work.
