### ISSUE TITLE
Is always collide with "CapsuleComponent ("CollisionCylinder") "?

### ISSUE THREAD

**Issue by Yukkitio** [rlewicki/MeleeTrace#3]
I want to make your system dynamic by having a good hitbox system but the system actually trigger a hit when i collide with that but i want to make it collide not on that but on other Capsule Collision (like on the head socket) so he need to not beeing trigger when hitting the Capsule Component.
![image](https://github.com/rlewicki/MeleeTrace/assets/50698691/8b971910-b8e2-4a3c-9b2a-00a1fed3c04d)
![image (2)](https://github.com/rlewicki/MeleeTrace/assets/50698691/1545b459-4573-47fa-ae05-3788a1d24866)

Can you help me with that ? ^^' 
thanks a lot for this plugin !

**Comment by rlewicki** [comment]
Hey @Yukkitio, if you want the trace to be detected on specific components, the best way to do that would be to create a new trace channel in project settings and then use it in the Melee Trace Settings tab (https://github.com/rlewicki/MeleeTrace/wiki#project-settings). In your case, I'd recommend setting default response to the trace channel to `Ignore` and then for every component you want the trace to collide with, change the response to `Block`.

Hope this helps, let me know if you need further help!

**Comment by Yukkitio** [comment]
Sorry i don't understand how i could do it cause in project setting there is no Ignore.
<img width="860" alt="image" src="https://github.com/rlewicki/MeleeTrace/assets/50698691/7d3a0c00-8e01-4cf5-9993-7b41f62fb578">

**Comment by rlewicki** [comment]
You need to search for `Collision` under `Engine` category. There you can create new trace channel. For more information on how collision channels work please refer to the engine docs: https://docs.unrealengine.com/4.26/en-US/InteractiveExperiences/Tracing/Overview/

![obraz](https://github.com/rlewicki/MeleeTrace/assets/10658394/baefd067-28eb-47a9-bc18-3813c105bcb4)

**Comment by sethseth2** [comment]
Piggybacking here ~

So to clarify - I have made a collision channel for all of my abilities (projectiles, etc., that need to overlap with enemies hit boxes - not their skeletal meshes). I should make a _separate_ channel specific to the Melee Trace, and then customize the settings of that channel to only interact with the hitbox? 🤔

**Comment by rlewicki** [comment]
Hey @sethseth2. I'd say it's the other way around. So if you want to have a full control over what the trace is detecting I would suggest the following:
1. Go to project settings, collision and create new trace channel, call it e.g. `Melee` or `MeleeTrace`. Set it's default response to `Ignore`.
2. Now unfold the `Presets` and open the ones you are interested in and modify them to `Block` the `Melee` trace channel.
3. If you have new type of objects like bullets or abilities you can create new preset for each of them and set collision to `Block`.

Answering second question - only blocking is detected as overlapping only affects physics, it does not affect tracing (unless you specifically trace for overlaps which is possible).

Hope this helps you a bit, in case of further questions please don't hesitate to ask!
