### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by travisbales2304** [rlewicki/MeleeTrace#4]
for the OnTraceHit can you add the hit bone as an output to determine headshots and such?

**Comment by rlewicki** [comment]
Hey @travisbales2304, absolutely. I will give my best to add it this weekend.

**Comment by rlewicki** [comment]
Hey @travisbales2304 just wanted to let you know that latest version from master now has bone name on the trace hit delegate. It will take some time to publish it to the marketplace though so if you want to to test it now feel free to download the zip file from GitHub.

**Comment by travisbales2304** [comment]
Awesome, Love the feedback. I apologize for the late response. I have been working on other aspects of my project since then.
