### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by unreal79** [rlewicki/MeleeTrace#5]
Is there example project?

**Comment by unreal79** [comment]
Ok, I slapped together some meshes and custom (ugly) animation, and setup Melee Trace system (that was surprisingly easy). Works great! Do you want the example project?

**Comment by rlewicki** [comment]
Hi @unreal79, I have my pet project where I test my changes however I cannot make it publicly available due to license issue as I'm using some other marketplace assets.  If you have a project and can make it available on GitHub I am more than happy to link it in the README description!

**Comment by unreal79** [comment]
Here is the example project: https://github.com/unreal79/Melee-Trace-Example-1 -- if you wish, you may fork it.

Thanks a lot for your hard work with the plugin. Really appreciate it!
